---
- name: Power ON "{{ rru }}" with the SophiaNode R2Lab helper
  ansible.builtin.shell: |
    set -e
    source ~/.bashrc
    rhubarbe-pdu on "{{ rru }}"
  args:
    executable: /bin/bash
  delegate_to: faraday.inria.fr

- name: Allow N3xx RRU to complete its cold boot
  ansible.builtin.pause:
    seconds: 60
  when: rru in ['n300', 'n320']
